USE CODEGNAN;

CREATE TABLE EMP5 (ID INT,EMPNAME VARCHAR(50),CITY VARCHAR(20));

INSERT INTO EMP5 VALUES (1,"SAI VARDHAN","LONDAN"),(2,"VISHNU VARDHAN","LONDEN"),(3,"VENKAT","INDIA"),(4,"VENKOT","INDIA");

SELECT * FROM EMP5;

-- CONCAT
SELECT CONCAT("SAI"," ","VARDHAN") AS FULLNAME;
SELECT CONCAT(EMPNAME," PLCAE IS ",CITY) AS DETAILS FROM EMP5;

-- CONCAT_WS
SELECT (CONCAT_WS(" , ","SAI","VARDHAN","VENKATE","VENKATESH")) AS NAMESS;
SELECT CONCAT_WS(", ",EMPNAME,CITY) AS DETAILS FROM EMP5;

-- LOWER AND UPPER
SELECT UPPER("Hello") as capital;
SELECT LOWER("hellO") AS LOWER;

SELECT EMPNAME,UPPER(EMPNAME) AS CAPITAL, CITY, LOWER(CITY) AS SMALL FROM EMP5;

-- LENGTH

SELECT LENGTH("Hello") as LENGTH;
SELECT char_length("Hrllo") as CHARLENGTH;

SELECT ID,LENGTH(EMPNAME) AS NAMELENGTH, CHAR_LENGTH(EMPNAME) AS NAMECHARLENGTH FROM EMP5;

-- SUB STRING
SELECT SUBSTRING("VENKATESH",6);
SELECT SUBSTRING("VENKATESH",2,6);

SELECT EMPNAME,SUBSTRING(EMPNAME,2,5) AS SUBSTRR FROM EMP5;

-- REVERSE
SELECT REVERSE("SAI") AS REV;

SELECT ID,EMPNAME,REVERSE(EMPNAME) AS REVNAME FROM EMP5;

-- REPLACE
SELECT REPLACE("SAI VARDHAN","SAI","I") AS REPLCAED_STRING;

SELECT ID,EMPNAME,REPLACE(EMPNAME,"SAI","I") AS REPLACED_STRING FROM EMP5;

-- LIKE(%)
SELECT "SAI VARDHAN" LIKE "VARDHAN%" AS XYZ;
SELECT "SAI VARDHAN" LIKE "S_I VARDHAN" AS ABC;

SELECT * FROM EMP5 WHERE CITY LIKE "IA";
SELECT * FROM EMP5 WHERE CITY LIKE "LOND_N";