USE CODEGNAN;

CREATE TABLE CUSTOMERS (
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(50),
    AGE INT,
    STATUS VARCHAR(10)
);

INSERT INTO CUSTOMERS (NAME,AGE,STATUS) VALUES ("SAI",28,"MAJOR"),("VARDHAN",18,"MAJOR"),("VENKAT",17,"MINOR");

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS (NAME,AGE) VALUES ("SAI1",18),("SAI2",16),("SAI3",18),("SAI4",8);

SELECT * FROM CUSTOMERS;

SELECT NAME,(ID+AGE) AS NEWDATA FROM CUSTOMERS;

SELECT NAME,ID,AGE,(AGE-ID) AS NEWDATA FROM CUSTOMERS;

SELECT NAME,ID,AGE,(ID*10) AS NEWDATA FROM CUSTOMERS;

SELECT NAME,ID,AGE,(AGE/2) AS NEWDATA FROM CUSTOMERS;

SELECT NAME,ID,AGE,(AGE%2) AS NEWDATA FROM CUSTOMERS;

